version: '3'

services:
  frontend:
    build: angular-client
    ports:
      - "4200:4200"
    container_name: front-container
    #restart: always
    volumes:
      - ./angular-client/src:/usr/src/app/src

  backend:
    build: express-server
    ports:
      - "3000:3000"
      - "9229:9229"
    container_name: back-container
    #restart: always
    volumes:
      - ./express-server:/usr/src/app
      - /usr/src/app/node_modules # exclude from volume
    links:
      - database

  database:
    image: 'postgres:11.5-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRESS_DB=postgres
    ports:
      - "5432:5432"
    container_name: database-container
    #restart: always
